#!/usr/bin/env bash


NEXTCLOUD_CREDENTIALS=$1
DOCKERHUB_CREDENTIALS=$2


DOCKER_USER=${DOCKERHUB_CREDENTIALS%%:*}
DOCKER_PWD=${DOCKERHUB_CREDENTIALS##*:}

echo "User $DOCKER_USER"
echo "PWD $DOCKER_PWD"